version: "3.5"

services:
  database:
    image: mongo
    container_name: flexi_guitar_mongodb
    environment:
      - MONGO_INITDB_DATABASE=flexi_guitar
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
